# Generated by Django 6.0.4 on 2026-04-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
            ],
            options={
                'verbose_name_plural': 'ギャラリー写真',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='メイン画像')),
                ('content', models.TextField(verbose_name='本文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日')),
            ],
            options={
                'verbose_name_plural': 'ブログ記事',
                'ordering': ['-created_at'],
            },
        ),
    ]
